import { Roll } from "@/app/globalInterfaces";

export let defaultRolls: Roll[] = [
  {
    id: "0",
    name: "Initiative",
    roll: "d20 + var(dex)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    id: "1",
    name: "Acrobatics",
    roll: "d20 + var(dex)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    id: "2",
    name: "Animal_Handling",
    roll: "d20 +var(wis)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    id: "3",
    name: "Arcana",
    roll: "d20 + var(int)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    id: "4",
    name: "Athletics",
    roll: "d20 + var(str)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    id: "5",
    name: "Deception",
    roll: "d20 + var(cha)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    id: "6",
    name: "History",
    roll: "d20 + var(int)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    id: "7",
    name: "Insight",
    roll: "d20 + var(wis)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    id: "8",
    name: "Intimidation",
    roll: "d20 + var(cha)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    id: "9",
    name: "Investigation",
    roll: "d20 + var(int)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    id: "10",
    name: "Medicine",
    roll: "d20 + var(wis)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    id: "11",
    name: "Nature",
    roll: "d20 + var(int)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    id: "12",
    name: "Perception",
    roll: "d20 + var(wis)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    id: "13",
    name: "Performance",
    roll: "d20 + var(cha)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    id: "14",
    name: "Persuasion",
    roll: "d20 + var(cha)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    id: "15",
    name: "Religion",
    roll: "d20 + var(int)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    id: "16",
    name: "Slight_of_Hand",
    roll: "d20 + var(dex)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    id: "17",
    name: "Stealth",
    roll: "d20 + var(dex)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    id: "18",
    name: "Survival",
    roll: "d20 + var(wis)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    id: "19",
    name: "Strength_Save",
    roll: "d20 + var(str)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    id: "20",
    name: "Dexterity_Save",
    roll: "d20 + var(dex)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    id: "21",
    name: "Constitution_Save",
    roll: "d20 + var(con)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    id: "22",
    name: "Intelligence_Save",
    roll: "d20 + var(int)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    id: "23",
    name: "Wisdom_Save",
    roll: "d20 + var(wis)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    id: "24",
    name: "Charisma_Save",
    roll: "d20 + var(cha)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
];
