import { Roll } from "@/app/globalInterfaces";
export let defaultRolls: Roll[] = [
  {
    name: "Initiative",
    roll: "d20 + var(dex)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    name: "Acrobatics",
    roll: "d20 + var(dex)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    name: "Animal_Handling",
    roll: "d20 +var(wis)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    name: "Arcana",
    roll: "d20 + var(int)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    name: "Athletics",
    roll: "d20 + var(str)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    name: "Deception",
    roll: "d20 + var(cha)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    name: "History",
    roll: "d20 + var(int)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    name: "Insight",
    roll: "d20 + var(wis)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    name: "Intimidation",
    roll: "d20 + var(cha)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    name: "Investigation",
    roll: "d20 + var(int)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    name: "Medicine",
    roll: "d20 + var(wis)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    name: "Nature",
    roll: "d20 + var(int)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    name: "Perception",
    roll: "d20 + var(wis)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    name: "Performance",
    roll: "d20 + var(cha)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    name: "Persuasion",
    roll: "d20 + var(cha)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    name: "Religion",
    roll: "d20 + var(int)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    name: "Slight_of_Hand",
    roll: "d20 + var(dex)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    name: "Stealth",
    roll: "d20 + var(dex)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    name: "Survival",
    roll: "d20 + var(wis)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    name: "Strength_Save",
    roll: "d20 + var(str)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    name: "Dexterity_Save",
    roll: "d20 + var(dex)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    name: "Constitution_Save",
    roll: "d20 + var(con)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    name: "Intelligence_Save",
    roll: "d20 + var(int)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    name: "Wisdom_Save",
    roll: "d20 + var(wis)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
  {
    name: "Charisma_Save",
    roll: "d20 + var(cha)",
    healthCost: "0",
    manaCost: "0",
    actionTypes: [],
    conditions: [],
  },
];
